### ISSUE TITLE
The use of `tuple` in annotations is Python 3.9

### ISSUE THREAD

**Issue by lezcano** [Quansight-Labs/numpy_pytorch_interop#111]
See https://docs.python.org/3/library/typing.html#typing.Tuple. Accordingly, we should `from __future__ import annotations`. Now, interestingly enough, when doing that in the impl files, the annotated type of the variable returned by `inspect.signature["param"].annotation` happens to be a string... 
Not sure what's going on there (perhaps @rgommers knows?), but we should test all this with Python 3.8 as it's the oldest Python that PyTorch supports.

**Comment by lezcano** [comment]
I wanted to use the import as it's more future proof. `typing.Tuple` is deprecated as of 3.9.

**Comment by rgommers** [comment]
that doesn't ring any bells, sorry. I'd have thought that this should "just work" with `from __future__ import annotations`

**Comment by lezcano** [comment]
Changing the dict to strings and adding the `from future import...` to all the files that use the annotations seems like the right approach. I might send a PR later this week with this change and a few other proposals if I find the time.
