### ISSUE TITLE
Not preserving dtype when passing in numpy.ndarray

### ISSUE THREAD

**Issue by larryliu0820** [Quansight-Labs/numpy_pytorch_interop#136]
```python
>>> import numpy as np
>>> import torch_np
>>> a = np.ones([1, 3], dtype=np.float32)
>>> a.dtype
dtype('float32')
>>> b = torch_np.add(a, 1)
>>> b.dtype
dtype("float64")
>>> c = np.add(a, 1)
>>> c.dtype
dtype('float32')
```

When we call `torch_np` APIs with numpy.ndarray, we should preserve the dtype. Instead we are getting `float64` all the time.

**Comment by ev-br** [comment]
The OP example is an instance of the _scalar do not upcast arrays_ rule:

```
In [14]: np.add(np.array(2, dtype=np.float32), 1).dtype       # 0D array + python scalar, type promotion
Out[14]: dtype('float64')

In [15]: np.add(np.array([2, 3], dtype=np.float32), 1).dtype    1D array + python scalar, array wins
Out[15]: dtype('float32')
```

We do not implement this rule indeed. 

Taking a step back, why do you need to mix numpy arrays with torch_np arrays? This should not happen in practice, I'd think.

**Comment by larryliu0820** [comment]
I think it's due to this piece:
https://github.com/Quansight-Labs/numpy_pytorch_interop/blob/main/torch_np/_util.py#L201-L211

If the object is numpy.ndarray, `torch.as_tensor(obj)` does the right thing of keeping the dtype. However I'm not sure why we choose to cast it to "default dtype" in this case.

> Taking a step back, why do you need to mix numpy arrays with torch_np arrays? This should not happen in practice, I'd think.

I'm working on a PR https://github.com/pytorch/pytorch/pull/100839 and we do have a scenario where we need to feed numpy.ndarray into torch_np APIs, see this comment https://github.com/pytorch/pytorch/pull/100839#discussion_r1189302096

**Comment by ev-br** [comment]
The cast to essentially float64 is to avoid float32 overflows. The snippet in the comment is real.

Now, I don't claim deep understanding of the context behind https://github.com/pytorch/pytorch/pull/100839#discussion_r1189302096, if you are encountering an np.ndarray and need to convert it to something from torch.dynamo, and your layer is already numpy-aware, can you just convert it to a tensor? That would preserve the dtype, I believe.

**Comment by larryliu0820** [comment]
ok let me look more into it.

**Comment by larryliu0820** [comment]
@ev-br Is it really bad if we have a special case in `_coerce_to_tensor()` where we don't promote to default dtype, if the object is numpy.ndarray?

**Comment by ev-br** [comment]
The issue is that this layer knows nothing about numpy.

**Comment by lezcano** [comment]
About https://github.com/Quansight-Labs/numpy_pytorch_interop/issues/136#issuecomment-1542775760 and @ezyang comments. Evgeni is right. This layer knows nothing about NumPy and shouldn't. `torch_np` operations or arrays should never be executed on NumPy arrays or operations. Same thing in the opposite direction.

**Comment by larryliu0820** [comment]
@ev-br @lezcano make sense. Thanks!
