### ISSUE TITLE
min/max for complex inputs

### ISSUE THREAD

**Issue by ev-br** [Quansight-Labs/numpy_pytorch_interop#67]
Pytorch throws `RuntimeError: "min_values_cpu" not implemented for 'ComplexDouble'`. Numpy does something: looks like it compares the real part and breaks ties with the imaginary part.

There are some tests in `numpy_tests/core/test_multiarray.py::TestArgmax::test_combinations` and `...::TestArgmin::...`

**Comment by ev-br** [comment]
A similar issue exists for sorting and searching: `argmin`, `argmax` and `searchsorted`.

https://github.com/Quansight-Labs/numpy_pytorch_interop/pull/65#pullrequestreview-1315392268 and https://github.com/Quansight-Labs/numpy_pytorch_interop/pull/65#discussion_r1118617329 suggest to just disallow it:

>  What does it even mean to sort a complex anything?

I *think* numpy does essentially a lexicographic ordering: compare real parts and break ties with the imaginary part. Not sure though, and would rather agree that an arbitrary decision on how to impose order in the complex plane best needs a motivating use case.

**Comment by rgommers** [comment]
+1 to disallow

**Comment by ev-br** [comment]
added to the list of current limitations in gh-73

**Comment by ev-br** [comment]
This is tracked / mentioned on gh-73, so let's close this.
