### ISSUE TITLE
Add packaging support?

### ISSUE THREAD

**Issue by larryliu0820** [Quansight-Labs/numpy_pytorch_interop#74]
A `pyproject.toml` and/or a `setup.py` would be appreciated. I can send a PR, but I think it's better to include `LICENSE` as well as `README.md` into the package as well.

**Comment by larryliu0820** [comment]
see #75

**Comment by rgommers** [comment]
Good question about `LICENSE` and `README.md`. This package is meant for upstreaming into PyTorch, so let's say so in the README (and add a bit more context about the goals) and LICENSE.

I will note that we don't have a CLA bot on this repo, so let's be careful with accepting contributions from outside of Quansight and Meta @ev-br.

**Comment by ev-br** [comment]
Now that we have pyproject.toml and setup.py, is there anything left to be done. I'll close, please comment/reopen if there's anything missing.
